{% set name = "modflow-export" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/modflow-export-{{ version }}.tar.gz
  sha256: 1f51952c2e049a61c08cf50aa6fb3f6d8c2ef6d6587f537a60f484ea7c642a7b

build:
  entry_points:
    - get-modflow = flopy.utils.get_modflow:cli_main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.11
    - setuptools >=61
    - pip
  run:
    - python >=3.11
    - gis-utils
    - fiona
    - flopy
    - matplotlib-base
    - numpy
    - pandas
    - pyproj
    - pyyaml
    - rasterio
    - shapely
    - xarray

test:
  imports:
    - mfexport
  commands:
    - pip check
    - get-modflow --help
  requires:
    - pip

about:
  home: https://github.com/aleaf/modflow-export
  summary: Fast & easy summarizing of MODFLOW data and export to GIS file formats
  license: CC0-1.0
  license_file: LICENSE.md
  doc_url: https://aleaf.github.io/modflow-export/latest/

extra:
  recipe-maintainers:
    - aleaf
    - jdhughes-usgs
